import { and, eq, gte, lte } from 'drizzle-orm';
import { db, factOrgDaily, factOrgDailyByFeature, factOrgDailyByIde, factOrgDailyByModelFeature, factBillingDaily } from '@ghcp-dash/db';
import type { AdoptionResponse } from '@ghcp-dash/contracts';
import type { DateRange } from '@/lib/date-range';
import { n, safeDiv, safeQuery } from './common';
const empty: AdoptionResponse = { headlines: { dau: 0, wau: 0, mau: 0, wauSeatRatio: 0, acceptanceRate: 0, agentAdoptionPct: 0 }, dauWauTrend: [], acceptanceRateTrend: [], chatModeBreakdown: [], topIdes: [], topModels: [], funnel: [] };
export async function queryAdoption(orgId: string, range: DateRange): Promise<AdoptionResponse> { return safeQuery(empty, async () => { const [orgRows, featureRows, ideRows, modelRows, billingRows] = await Promise.all([db.select().from(factOrgDaily).where(and(eq(factOrgDaily.orgId, orgId), gte(factOrgDaily.day, range.from), lte(factOrgDaily.day, range.to))), db.select().from(factOrgDailyByFeature).where(and(eq(factOrgDailyByFeature.orgId, orgId), gte(factOrgDailyByFeature.day, range.from), lte(factOrgDailyByFeature.day, range.to))), db.select().from(factOrgDailyByIde).where(and(eq(factOrgDailyByIde.orgId, orgId), gte(factOrgDailyByIde.day, range.from), lte(factOrgDailyByIde.day, range.to))), db.select().from(factOrgDailyByModelFeature).where(and(eq(factOrgDailyByModelFeature.orgId, orgId), gte(factOrgDailyByModelFeature.day, range.from), lte(factOrgDailyByModelFeature.day, range.to))), db.select().from(factBillingDaily).where(and(eq(factBillingDaily.orgId, orgId), gte(factBillingDaily.day, range.from), lte(factBillingDaily.day, range.to))) ]); const latest = orgRows.at(-1); const seats = billingRows.reduce((m, r) => Math.max(m, n(r.quantity)), 0); const accepted = orgRows.reduce((s,r)=>s+r.codeAcceptanceActivityCount,0); const generated = orgRows.reduce((s,r)=>s+r.codeGenerationActivityCount,0);
const chatMap = new Map<string, { day:string; ask:number; edit:number; plan:number; agent:number }>(); for (const r of featureRows) { const day=String(r.day); const row=chatMap.get(day) ?? { day, ask:0, edit:0, plan:0, agent:0 }; const f = r.feature.toLowerCase(); if (f.includes('ask')) row.ask += r.userInitiatedInteractionCount; else if (f.includes('edit')) row.edit += r.userInitiatedInteractionCount; else if (f.includes('plan')) row.plan += r.userInitiatedInteractionCount; else if (f.includes('agent')) row.agent += r.userInitiatedInteractionCount; chatMap.set(day,row); }
const topIdes = [...ideRows.reduce((m,r)=>m.set(r.ide,(m.get(r.ide)??0)+r.userInitiatedInteractionCount), new Map<string,number>())].map(([ide,count])=>({ide,count})).sort((a,b)=>b.count-a.count).slice(0,8); const topModels = [...modelRows.reduce((m,r)=>m.set(r.model,(m.get(r.model)??0)+r.userInitiatedInteractionCount), new Map<string,number>())].map(([model,count])=>({model,count})).sort((a,b)=>b.count-a.count).slice(0,8);
return { headlines: { dau: latest?.dailyActiveUsers ?? 0, wau: latest?.weeklyActiveUsers ?? 0, mau: latest?.monthlyActiveUsers ?? 0, wauSeatRatio: safeDiv(latest?.weeklyActiveUsers ?? 0, seats), acceptanceRate: safeDiv(accepted, generated), agentAdoptionPct: safeDiv(latest?.monthlyActiveAgentUsers ?? 0, latest?.monthlyActiveUsers ?? 0) }, dauWauTrend: orgRows.map(r=>({day:String(r.day), dau:r.dailyActiveUsers, wau:r.weeklyActiveUsers})), acceptanceRateTrend: orgRows.map(r=>({day:String(r.day), rate:safeDiv(r.codeAcceptanceActivityCount,r.codeGenerationActivityCount)})), chatModeBreakdown: [...chatMap.values()].sort((a,b)=>a.day.localeCompare(b.day)), topIdes, topModels, funnel: [{stage:'Licensed', count:seats},{stage:'Active', count:latest?.monthlyActiveUsers??0},{stage:'Chat', count:latest?.monthlyActiveChatUsers??0},{stage:'Agent', count:latest?.monthlyActiveAgentUsers??0}] }; }); }
