import { and, eq, gte, lte } from 'drizzle-orm';
import { db, factOrgDaily, factOrgDailyByFeature, factOrgDailyByIde, factOrgDailyByLanguageFeature, factOrgDailyByModelFeature } from '@ghcp-dash/db';
import type { CodeGenResponse } from '@ghcp-dash/contracts';
import type { DateRange } from '@/lib/date-range';
import { n, safeDiv, safeQuery } from './common';
const empty: CodeGenResponse = { headlines:{locAdded:0,locDeleted:0,locChanged:0,acceptanceRate:0,agentContributionPct:0}, dailyLoc:[], byLanguage:[], byFeature:[], byIde:[], byChatMode:[], byModel:[] };
export async function queryCodeGeneration(orgId:string, range:DateRange):Promise<CodeGenResponse>{return safeQuery(empty, async()=>{const [orgRows, featureRows, ideRows, langRows, modelRows]=await Promise.all([db.select().from(factOrgDaily).where(and(eq(factOrgDaily.orgId,orgId),gte(factOrgDaily.day,range.from),lte(factOrgDaily.day,range.to))),db.select().from(factOrgDailyByFeature).where(and(eq(factOrgDailyByFeature.orgId,orgId),gte(factOrgDailyByFeature.day,range.from),lte(factOrgDailyByFeature.day,range.to))),db.select().from(factOrgDailyByIde).where(and(eq(factOrgDailyByIde.orgId,orgId),gte(factOrgDailyByIde.day,range.from),lte(factOrgDailyByIde.day,range.to))),db.select().from(factOrgDailyByLanguageFeature).where(and(eq(factOrgDailyByLanguageFeature.orgId,orgId),gte(factOrgDailyByLanguageFeature.day,range.from),lte(factOrgDailyByLanguageFeature.day,range.to))),db.select().from(factOrgDailyByModelFeature).where(and(eq(factOrgDailyByModelFeature.orgId,orgId),gte(factOrgDailyByModelFeature.day,range.from),lte(factOrgDailyByModelFeature.day,range.to))) ]); const locAdded=orgRows.reduce((s,r)=>s+n(r.locAddedSum),0), locDeleted=orgRows.reduce((s,r)=>s+n(r.locDeletedSum),0); const accepted=orgRows.reduce((s,r)=>s+r.codeAcceptanceActivityCount,0), generated=orgRows.reduce((s,r)=>s+r.codeGenerationActivityCount,0); const agentLoc=featureRows.filter(r=>/agent|edit/i.test(r.feature)).reduce((s,r)=>s+n(r.locAddedSum),0);
const dailyMap=new Map<string,{day:string;userInitiatedAdded:number;userInitiatedDeleted:number;agentInitiatedAdded:number;agentInitiatedDeleted:number}>(); for(const r of featureRows){const day=String(r.day); const row=dailyMap.get(day)??{day,userInitiatedAdded:0,userInitiatedDeleted:0,agentInitiatedAdded:0,agentInitiatedDeleted:0}; if(/agent|edit/i.test(r.feature)){row.agentInitiatedAdded+=n(r.locAddedSum); row.agentInitiatedDeleted+=n(r.locDeletedSum);} else {row.userInitiatedAdded+=n(r.locAddedSum); row.userInitiatedDeleted+=n(r.locDeletedSum);} dailyMap.set(day,row);} const sumBy=<K extends string>(rows:any[], key:K, label:string)=>[...rows.reduce((m,r)=>m.set(r[key],(m.get(r[key])??0)+n(r.locAddedSum)),new Map<string,number>())].map(([v,loc])=>({[label]:v,loc} as any)).sort((a:any,b:any)=>b.loc-a.loc).slice(0,10);
return { headlines:{locAdded, locDeleted, locChanged:locAdded+locDeleted, acceptanceRate:safeDiv(accepted,generated), agentContributionPct:safeDiv(agentLoc,locAdded)}, dailyLoc:[...dailyMap.values()].sort((a,b)=>a.day.localeCompare(b.day)), byLanguage:sumBy(langRows,'language','language'), byFeature:sumBy(featureRows,'feature','feature'), byIde:sumBy(ideRows,'ide','ide'), byChatMode:sumBy(featureRows.filter(r=>/ask|edit|plan|chat|agent/i.test(r.feature)),'feature','mode'), byModel:sumBy(modelRows,'model','model')};});}
