import { createHash } from 'node:crypto';
import { and, eq, inArray, isNotNull, ne, sql } from 'drizzle-orm';
import { loadEnvFromWorkspaceRoot } from './load-env.js';
import {
  computeDailyValue,
  DEFAULT_KNOBS,
  snapshotKnobs,
  type SpendDailyInputs,
  type ValueKnobs,
} from '@ghcp-dash/value';
import { createDb, type Database } from './client.js';
import {
  bridgeUserTeam,
  dimFeature,
  dimIde,
  dimLanguage,
  dimModel,
  dimOrg,
  dimRepo,
  dimTeam,
  dimUser,
  factAiCreditsDaily,
  factBillingDaily,
  factCiDaily,
  factCommitDaily,
  factDoraDaily,
  factOrgDaily,
  factOrgDailyByFeature,
  factOrgDailyByIde,
  factOrgDailyByLanguageFeature,
  factOrgDailyByLanguageModel,
  factOrgDailyByModelFeature,
  factRoiDaily,
  factReleaseDaily,
  factTeamValueDaily,
  factUserDaily,
  factUserDailyByFeature,
  factUserDailyByIde,
  factUserDailyByLanguageFeature,
  factUserDailyByLanguageModel,
  factUserDailyByModelFeature,
  factValueDaily,
  factWorkflowRunDaily,
  ingestionRun,
  settings,
  VALUE_TRANSLATION_KNOBS_KEY,
} from './schema/index.js';

// ============================================================================
// .env discovery (walk up from cwd)
// ============================================================================

loadEnvFromWorkspaceRoot();

// ============================================================================
// Constants
// ============================================================================

/**
 * Marker text written into `dim_org.display_name` for synthetic demo orgs so
 * the `--clear-demo` action can scrub demo data without touching real orgs.
 */
const DEMO_ORG_MARKER = '[demo]';

/** Slug for the synthetic org generated by `--demo`. */
const DEMO_ORG_SLUG = 'demo-org';

/** How many days of synthetic history to generate. */
const DEMO_DAYS = 90;

/** Synthetic repository ids for delivery-quality demo data. */
const DEMO_REPO_BASE_ID = 950_000_000;

const DEMO_REPOS = ['web-app', 'api', 'infra', 'mobile', 'docs'] as const;

// Canonical reference data — spec 01 §5.1.
const FEATURES = ['code_completion', 'chat', 'agent', 'cli', 'review', 'edit', 'plan', 'ask'] as const;
const IDES = ['vscode', 'jetbrains', 'xcode', 'visual_studio', 'neovim', 'unknown'] as const;
const LANGUAGES = ['typescript', 'python', 'go', 'java', 'javascript', 'csharp', 'rust', 'unknown'] as const;
const MODELS = ['gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'claude-3.5-sonnet', 'claude-sonnet-4', 'o1', 'unknown'] as const;
const DEMO_TEAMS = ['platform', 'productivity', 'data-ai', 'customer-apps', 'infra'] as const;

// ============================================================================
// CLI argument parsing
// ============================================================================

interface CliOptions {
  demo: boolean;
  clearDemo: boolean;
  reset: boolean;
  yes: boolean;
  help: boolean;
}

interface ReleaseEvent {
  day: string;
  isPrerelease: boolean;
  tagAt: Date | null;
}

interface CommitEvent {
  day: string;
  authoredAt: Date;
}

interface WorkflowRun {
  workflowId: number;
  conclusion: 'success' | 'failure' | 'cancelled';
  startedAt: Date;
  completedAt: Date | null;
  attempt: number;
}

interface DeliveryValueFunctions {
  deploymentFrequency(releases: ReleaseEvent[], daysInWindow: number): number | null;
  leadTimeForChanges(commits: CommitEvent[], releases: ReleaseEvent[]): number | null;
  changeFailureRate(releases: ReleaseEvent[], reverts: never[]): number | null;
  meanTimeToRestore(incidents: never[]): number | null;
  ciSuccessRate(runs: WorkflowRun[]): number | null;
  medianTimeToGreen(runs: WorkflowRun[]): number | null;
  flakyTestRate(runs: WorkflowRun[]): number | null;
}

function parseArgs(argv: readonly string[]): CliOptions {
  return {
    demo: argv.includes('--demo'),
    clearDemo: argv.includes('--clear-demo'),
    reset: argv.includes('--reset'),
    yes: argv.includes('--yes') || argv.includes('-y'),
    help: argv.includes('--help') || argv.includes('-h'),
  };
}

function printHelp(): void {
  console.log(`
Usage: pnpm db:seed [options]

Options:
  (no flags)       Seed dimension tables + default settings only (idempotent, production-safe).
  --demo           Also generate ${DEMO_DAYS} days of synthetic data for a "${DEMO_ORG_SLUG}" org.
  --clear-demo     Delete only the synthetic demo data (real org data is untouched).
  --reset --yes    DANGEROUS: delete ALL ingested fact data (silver + gold + ingestion_run).
                   Dimensions and settings are preserved.
  -h, --help       Show this help.

Examples:
  pnpm db:seed                  # bootstrap dims + settings
  pnpm db:seed --demo           # bootstrap + populate demo dashboard data
  pnpm db:seed --clear-demo     # remove demo data only
  pnpm db:seed --reset --yes    # nuclear: wipe all facts (keeps schema + dims)
`);
}

// ============================================================================
// Deterministic PRNG (mulberry32) so demo data is reproducible.
// ============================================================================

function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
  };
}

function jitter(rng: () => number, base: number, variance: number): number {
  return Math.max(0, Math.round(base + (rng() - 0.5) * 2 * variance));
}

// ============================================================================
// Date helpers
// ============================================================================

function todayUtc(): Date {
  const now = new Date();
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

function addDays(d: Date, n: number): Date {
  return new Date(d.getTime() + n * 86_400_000);
}

function isoDay(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function daysSequence(from: Date, count: number): string[] {
  return Array.from({ length: count }, (_, i) => isoDay(addDays(from, i)));
}

function dateAtUtc(day: string, hour: number, minute = 0, second = 0): Date {
  return new Date(`${day}T${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}Z`);
}

function toNumeric(value: number | null): string | null {
  return value === null ? null : String(value);
}

async function loadDeliveryValueFunctions(): Promise<DeliveryValueFunctions> {
  const doraModulePath = '../../value/src/dora.js';
  const ciModulePath = '../../value/src/ci.js';
  const dora = (await import(doraModulePath)) as Pick<
    DeliveryValueFunctions,
    'deploymentFrequency' | 'leadTimeForChanges' | 'changeFailureRate' | 'meanTimeToRestore'
  >;
  const ci = (await import(ciModulePath)) as Pick<
    DeliveryValueFunctions,
    'ciSuccessRate' | 'medianTimeToGreen' | 'flakyTestRate'
  >;
  return { ...dora, ...ci };
}

// ============================================================================
// Step 1: dimensions
// ============================================================================

async function seedDimensions(db: Database): Promise<void> {
  console.log('• dimensions: seeding reference data');
  await db.insert(dimFeature).values(FEATURES.map((name) => ({ name, displayName: name }))).onConflictDoNothing();
  await db.insert(dimIde).values(IDES.map((name) => ({ name, displayName: name }))).onConflictDoNothing();
  await db.insert(dimLanguage).values(LANGUAGES.map((name) => ({ name, displayName: name }))).onConflictDoNothing();
  await db.insert(dimModel).values(MODELS.map((name) => ({ name, displayName: name }))).onConflictDoNothing();
}

// ============================================================================
// Step 2: settings (knobs + pseudonym salt)
// ============================================================================

async function seedSettings(db: Database): Promise<void> {
  console.log('• settings: writing default knobs + pseudonym salt (if missing)');
  await db
    .insert(settings)
    .values({
      key: VALUE_TRANSLATION_KNOBS_KEY,
      value: DEFAULT_KNOBS as unknown as Record<string, unknown>,
      updatedAt: new Date(),
    })
    .onConflictDoNothing({ target: settings.key });
  const salt = createHash('sha256').update(`${Date.now()}-${Math.random()}`).digest('hex').slice(0, 32);
  await db
    .insert(settings)
    .values({ key: 'pseudonym_salt', value: salt as unknown as Record<string, unknown>, updatedAt: new Date() })
    .onConflictDoNothing({ target: settings.key });
}

// ============================================================================
// Step 3: demo data
// ============================================================================

async function seedDemoOrg(db: Database): Promise<void> {
  const today = todayUtc();
  const firstDay = isoDay(addDays(today, -DEMO_DAYS + 1));
  const lastDay = isoDay(today);
  await db
    .insert(dimOrg)
    .values({ orgId: DEMO_ORG_SLUG, displayName: `${DEMO_ORG_MARKER} Demo organization`, firstSeenDay: firstDay, lastSeenDay: lastDay })
    .onConflictDoUpdate({
      target: dimOrg.orgId,
      set: { displayName: `${DEMO_ORG_MARKER} Demo organization`, firstSeenDay: firstDay, lastSeenDay: lastDay },
    });
}

async function seedDemoUsers(db: Database, count: number): Promise<bigint[]> {
  const today = todayUtc();
  const firstDay = isoDay(addDays(today, -DEMO_DAYS + 1));
  const lastDay = isoDay(today);
  const saltRow = await db.select({ value: settings.value }).from(settings).where(eq(settings.key, 'pseudonym_salt')).limit(1);
  const pseudonymSalt = saltRow[0]?.value;
  if (typeof pseudonymSalt !== 'string' || pseudonymSalt.length === 0) {
    throw new Error('pseudonym_salt setting is required before seeding demo users.');
  }
  const ids: bigint[] = [];
  const rows = Array.from({ length: count }, (_, i) => {
    const userId = BigInt(900_000_000 + i + 1);
    ids.push(userId);
    const login = `demo-user-${String(i + 1).padStart(2, '0')}`;
    const pseudonym = createHash('sha256').update(`${pseudonymSalt}:${userId}:${login}`).digest('hex').slice(0, 16);
    return { userId, userLogin: login, pseudonym, firstSeenDay: firstDay, lastSeenDay: lastDay };
  });
  await db
    .insert(dimUser)
    .values(rows)
    .onConflictDoUpdate({
      target: dimUser.userId,
      set: { userLogin: sql`EXCLUDED.user_login`, pseudonym: sql`EXCLUDED.pseudonym`, lastSeenDay: lastDay },
    });
  return ids;
}

async function seedDemoTeams(db: Database): Promise<bigint[]> {
  const today = todayUtc();
  const firstDay = isoDay(addDays(today, -DEMO_DAYS + 1));
  const lastDay = isoDay(today);
  const ids = DEMO_TEAMS.map((_, i) => BigInt(940_000_000 + i + 1));
  const rows = DEMO_TEAMS.map((slug, i) => ({
    teamId: ids[i]!,
    orgId: DEMO_ORG_SLUG,
    slug,
    firstSeenDay: firstDay,
    lastSeenDay: lastDay,
  }));
  await db
    .insert(dimTeam)
    .values(rows)
    .onConflictDoUpdate({
      target: dimTeam.teamId,
      set: { orgId: DEMO_ORG_SLUG, slug: sql`EXCLUDED.slug`, lastSeenDay: lastDay },
    });
  return ids;
}

async function seedDemoRepos(db: Database): Promise<bigint[]> {
  const today = todayUtc();
  const firstDay = isoDay(addDays(today, -DEMO_DAYS + 1));
  const lastDay = isoDay(today);
  const repoIds: bigint[] = [];
  const rows = DEMO_REPOS.map((repoName, i) => {
    const repoId = BigInt(DEMO_REPO_BASE_ID + i + 1);
    repoIds.push(repoId);
    return {
      repoId,
      orgId: DEMO_ORG_SLUG,
      name: `${DEMO_ORG_SLUG}/${repoName}`,
      defaultBranch: 'main',
      firstSeenDay: firstDay,
      lastSeenDay: lastDay,
    };
  });

  console.log(`• demo: seeding ${rows.length} repositories`);
  await db
    .insert(dimRepo)
    .values(rows)
    .onConflictDoUpdate({
      target: dimRepo.repoId,
      set: {
        orgId: sql`EXCLUDED.org_id`,
        name: sql`EXCLUDED.name`,
        defaultBranch: 'main',
        firstSeenDay: firstDay,
        lastSeenDay: lastDay,
      },
    });
  return repoIds;
}

interface DailyProfile {
  day: string;
  dayIndex: number;
  isWeekend: boolean;
  activeUsers: number;
  totalCompletions: number;
  totalAccepted: number;
  totalLocAdded: number;
  totalLocDeleted: number;
  totalLocSuggestedAdd: number;
  totalLocSuggestedDelete: number;
  totalChatInteractions: number;
  totalAgentInteractions: number;
  prsCreated: number;
  prsCreatedByCopilot: number;
  prsMerged: number;
  prsMergedByCopilot: number;
  prsReviewed: number;
  prsReviewedByCopilot: number;
}

function generateDailyProfile(day: string, dayIndex: number, totalDays: number, rng: () => number): DailyProfile {
  const date = new Date(`${day}T00:00:00Z`);
  const dow = date.getUTCDay();
  const isWeekend = dow === 0 || dow === 6;
  const weekdayMultiplier = isWeekend ? 0.2 : 1;

  // Adoption growth curve: 5 → 35 users over the window.
  const growth = 5 + Math.round((totalDays === 1 ? 1 : dayIndex / (totalDays - 1)) * 30);
  const activeUsers = Math.max(1, jitter(rng, growth, 3));
  const baseCompletionsPerUser = jitter(rng, 35, 12) * weekdayMultiplier;
  const baseChatPerUser = jitter(rng, 14, 5) * weekdayMultiplier;
  const baseAgentPerUser = jitter(rng, 3, 1.5) * weekdayMultiplier;

  const totalCompletions = Math.max(isWeekend ? activeUsers * 6 : activeUsers * 20, Math.round(activeUsers * baseCompletionsPerUser));
  const acceptanceRate = 0.45 + rng() * 0.2;
  const totalAccepted = Math.round(totalCompletions * acceptanceRate);
  const locPerAcceptance = 4 + rng() * 6;
  const totalLocAdded = Math.max(isWeekend ? activeUsers * 24 : activeUsers * 60, Math.round(totalAccepted * locPerAcceptance));
  const totalLocDeleted = Math.max(isWeekend ? 6 : 12, Math.round(totalLocAdded * (0.1 + rng() * 0.15)));
  const totalLocSuggestedAdd = Math.max(
    Math.round(totalLocAdded / acceptanceRate),
    Math.round(totalCompletions * locPerAcceptance),
  );
  const totalLocSuggestedDelete = Math.max(
    Math.round(totalLocDeleted / acceptanceRate),
    Math.round(totalLocSuggestedAdd * (0.1 + rng() * 0.15)),
  );
  const totalChatInteractions = Math.max(isWeekend ? 6 : activeUsers * 4, Math.round(activeUsers * baseChatPerUser));
  const rawAgentInteractions = Math.round(activeUsers * baseAgentPerUser);
  const totalAgentInteractions = Math.min(
    Math.max(isWeekend ? 1 : Math.ceil(activeUsers * 0.4), rawAgentInteractions),
    Math.max(1, Math.floor(totalChatInteractions * 0.35)),
  );

  const prsCreated = isWeekend ? jitter(rng, 1, 1) : jitter(rng, 4 + dayIndex / 12, 2);
  const copilotPrShare = 0.35 + rng() * 0.25;
  const prsCreatedByCopilot = Math.round(prsCreated * copilotPrShare);
  const prsMerged = Math.max(0, prsCreated - jitter(rng, 1, 1));
  const prsMergedByCopilot = Math.min(prsMerged, prsCreatedByCopilot);
  const prsReviewed = prsCreated + jitter(rng, 1, 1);
  const prsReviewedByCopilot = Math.round(prsReviewed * (0.4 + rng() * 0.3));

  return {
    day,
    dayIndex,
    isWeekend,
    activeUsers,
    totalCompletions,
    totalAccepted,
    totalLocAdded,
    totalLocDeleted,
    totalLocSuggestedAdd,
    totalLocSuggestedDelete,
    totalChatInteractions,
    totalAgentInteractions,
    prsCreated,
    prsCreatedByCopilot,
    prsMerged,
    prsMergedByCopilot,
    prsReviewed,
    prsReviewedByCopilot,
  };
}

async function seedDemoReleaseFacts(db: Database, repoIds: readonly bigint[]): Promise<void> {
  const rng = mulberry32(20260620);
  const days = daysSequence(addDays(todayUtc(), -DEMO_DAYS + 1), DEMO_DAYS);
  console.log('• demo: seeding release aggregates');

  for (let dayIndex = 0; dayIndex < days.length; dayIndex += 1) {
    const day = days[dayIndex]!;
    const date = new Date(`${day}T00:00:00Z`);
    const isWeekend = date.getUTCDay() === 0 || date.getUTCDay() === 6;
    const releaseCount =
      isWeekend ? (rng() < 0.35 ? 1 : 0) + (rng() < 0.05 ? 1 : 0) : 1 + Math.floor(rng() * 3);

    const byRepo = new Map<bigint, { releaseCount: number; prereleaseCount: number; latestTagAt: Date }>();
    for (let r = 0; r < releaseCount; r += 1) {
      const repoId = repoIds[(dayIndex + r + Math.floor(rng() * repoIds.length)) % repoIds.length]!;
      const isPrerelease = rng() < 0.2;
      const tagAt = dateAtUtc(day, 13 + Math.floor(rng() * 6), Math.floor(rng() * 60));
      const current = byRepo.get(repoId) ?? { releaseCount: 0, prereleaseCount: 0, latestTagAt: tagAt };
      current.releaseCount += 1;
      current.prereleaseCount += isPrerelease ? 1 : 0;
      if (tagAt.getTime() > current.latestTagAt.getTime()) current.latestTagAt = tagAt;
      byRepo.set(repoId, current);
    }

    for (const [repoId, aggregate] of byRepo) {
      const values = {
        orgId: DEMO_ORG_SLUG,
        repoId,
        day,
        releaseCount: aggregate.releaseCount,
        prereleaseCount: aggregate.prereleaseCount,
        latestTagAt: aggregate.latestTagAt,
      };
      await db.insert(factReleaseDaily).values(values).onConflictDoUpdate({
        target: [factReleaseDaily.orgId, factReleaseDaily.repoId, factReleaseDaily.day],
        set: values,
      });
    }
  }
}

async function seedDemoWorkflowRunFacts(db: Database, repoIds: readonly bigint[]): Promise<void> {
  const rng = mulberry32(20260621);
  const days = daysSequence(addDays(todayUtc(), -DEMO_DAYS + 1), DEMO_DAYS);
  console.log('• demo: seeding workflow run aggregates');

  for (let dayIndex = 0; dayIndex < days.length; dayIndex += 1) {
    const day = days[dayIndex]!;
    const isWeekend = new Date(`${day}T00:00:00Z`).getUTCDay() % 6 === 0;
    const growth = 0.75 + (dayIndex / Math.max(1, days.length - 1)) * 0.5;

    for (let repoIndex = 0; repoIndex < repoIds.length; repoIndex += 1) {
      const repoId = repoIds[repoIndex]!;
      const workflowCount = repoIndex === 4 ? 2 : 3;
      for (let workflowOffset = 0; workflowOffset < workflowCount; workflowOffset += 1) {
        const workflowId = BigInt(Number(repoId) * 100 + workflowOffset + 1);
        const baseRuns = repoIndex === 4 ? 2 : 5 + repoIndex;
        const totalRuns = Math.max(1, Math.round(jitter(rng, baseRuns * growth * (isWeekend ? 0.35 : 1), 2)));
        const cancelledCount = rng() < 0.08 ? 1 : 0;
        const completedRuns = Math.max(0, totalRuns - cancelledCount);
        const baselineFailures = Math.floor(completedRuns * (0.025 + rng() * 0.035));
        const scheduledFailure =
          completedRuns >= 2 && (dayIndex + repoIndex + workflowOffset) % 6 === 0 ? 1 : 0;
        const failureCount = Math.min(
          completedRuns,
          baselineFailures + scheduledFailure + (completedRuns >= 8 && rng() < 0.05 ? 1 : 0),
        );
        const successCount = Math.max(0, completedRuns - failureCount);
        const medianDurationSec = jitter(rng, 180 + repoIndex * 70 + workflowOffset * 45, 60);
        const p90DurationSec = Math.round(medianDurationSec * (1.45 + rng() * 0.2));
        const values = {
          orgId: DEMO_ORG_SLUG,
          repoId,
          workflowId,
          day,
          successCount,
          failureCount,
          cancelledCount,
          medianDurationSec: String(medianDurationSec),
          p90DurationSec: String(p90DurationSec),
        };
        await db.insert(factWorkflowRunDaily).values(values).onConflictDoUpdate({
          target: [
            factWorkflowRunDaily.orgId,
            factWorkflowRunDaily.repoId,
            factWorkflowRunDaily.workflowId,
            factWorkflowRunDaily.day,
          ],
          set: values,
        });
      }
    }
  }
}

async function seedDemoCommitFacts(db: Database, repoIds: readonly bigint[], userIds: readonly bigint[]): Promise<void> {
  const rng = mulberry32(20260622);
  const days = daysSequence(addDays(todayUtc(), -DEMO_DAYS + 1), DEMO_DAYS);
  console.log('• demo: seeding commit aggregates');

  for (let dayIndex = 0; dayIndex < days.length; dayIndex += 1) {
    const day = days[dayIndex]!;
    const isWeekend = new Date(`${day}T00:00:00Z`).getUTCDay() % 6 === 0;
    const activeAuthors = Math.min(userIds.length, 5 + Math.round((dayIndex / Math.max(1, days.length - 1)) * 30));
    const pickedUsers = userIds.slice(0, activeAuthors);

    for (let repoIndex = 0; repoIndex < repoIds.length; repoIndex += 1) {
      const repoId = repoIds[repoIndex]!;
      const repoIntensity = [1.15, 1, 0.7, 0.85, 0.35][repoIndex] ?? 0.75;
      for (let authorIndex = 0; authorIndex < pickedUsers.length; authorIndex += 1) {
        const authorUserId = pickedUsers[authorIndex]!;
        const authorActivity = 0.25 + ((authorIndex % 7) / 10);
        const expected = repoIntensity * authorActivity * (isWeekend ? 0.25 : 1);
        const commitCount = Math.max(0, Math.round(expected + (rng() < expected % 1 ? 1 : 0) + (rng() < 0.08 ? 1 : 0)));
        if (commitCount === 0) continue;

        const additions = commitCount * jitter(rng, 70, 45);
        const deletions = Math.round(additions * (0.18 + rng() * 0.35));
        const values = {
          orgId: DEMO_ORG_SLUG,
          repoId,
          authorUserId,
          day,
          commitCount,
          additionsSum: BigInt(additions),
          deletionsSum: BigInt(deletions),
        };
        await db.insert(factCommitDaily).values(values).onConflictDoUpdate({
          target: [factCommitDaily.orgId, factCommitDaily.repoId, factCommitDaily.authorUserId, factCommitDaily.day],
          set: values,
        });
      }
    }
  }
}

async function seedDemoDeliveryFacts(db: Database, repoIds: readonly bigint[], userIds: readonly bigint[]): Promise<void> {
  await seedDemoReleaseFacts(db, repoIds);
  await seedDemoWorkflowRunFacts(db, repoIds);
  await seedDemoCommitFacts(db, repoIds, userIds);
}

const FEATURE_WEIGHTS: Array<[string, number]> = [
  ['code_completion', 0.6],
  ['chat', 0.18],
  ['agent', 0.1],
  ['edit', 0.06],
  ['ask', 0.04],
  ['plan', 0.02],
];
const IDE_WEIGHTS: Array<[string, number]> = [
  ['vscode', 0.7],
  ['jetbrains', 0.18],
  ['visual_studio', 0.07],
  ['neovim', 0.03],
  ['xcode', 0.02],
];
const IDE_INTERACTION_WEIGHTS: Array<[string, number]> = [
  ['vscode', 0.58],
  ['jetbrains', 0.22],
  ['visual_studio', 0.1],
  ['neovim', 0.06],
  ['xcode', 0.04],
];
const CHAT_INTERACTION_WEIGHTS: Array<[string, number]> = [
  ['chat', 0.35],
  ['ask', 0.3],
  ['edit', 0.23],
  ['plan', 0.12],
];
const LANGUAGE_WEIGHTS: Array<[string, number]> = [
  ['typescript', 0.32],
  ['python', 0.25],
  ['go', 0.13],
  ['java', 0.12],
  ['javascript', 0.1],
  ['csharp', 0.05],
  ['rust', 0.03],
];
const MODEL_WEIGHTS: Array<[string, number]> = [
  ['gpt-4o-mini', 0.25],
  ['gpt-4o', 0.3],
  ['claude-sonnet-4', 0.22],
  ['claude-3.5-sonnet', 0.13],
  ['gpt-4.1', 0.07],
  ['o1', 0.03],
];

function splitByWeightMap(total: number, weights: ReadonlyArray<readonly [string, number]>): Map<string, number> {
  const out = new Map<string, number>();
  let remaining = Math.max(0, Math.round(total));
  for (let i = 0; i < weights.length; i += 1) {
    const item = weights[i]!;
    const share =
      i === weights.length - 1 ?
        remaining
      : Math.min(remaining, Math.max(0, Math.round(total * item[1])));
    out.set(item[0], share);
    remaining -= share;
  }
  return out;
}

function buildFeatureInteractionShares(profile: DailyProfile): Map<string, number> {
  const out = splitByWeightMap(profile.totalChatInteractions, CHAT_INTERACTION_WEIGHTS);
  out.set('agent', profile.totalAgentInteractions);
  return out;
}

function userConsumptionShares(count: number): number[] {
  const raw = Array.from({ length: count }, (_, i) => 1 / (i + 1) ** 1.25);
  const total = raw.reduce((sum, value) => sum + value, 0);
  return raw.map((value) => value / total);
}

function teamForUserIndex(index: number, teamIds: readonly bigint[]): bigint {
  return teamIds[index % teamIds.length] ?? 940_000_001n;
}

async function seedDemoFacts(db: Database, userIds: readonly bigint[], teamIds: readonly bigint[]): Promise<void> {
  const rng = mulberry32(20260619);
  const days = daysSequence(addDays(todayUtc(), -DEMO_DAYS + 1), DEMO_DAYS);
  console.log(`• demo: generating ${days.length} days of fact data for "${DEMO_ORG_SLUG}"`);

  const profiles = days.map((day, i) => generateDailyProfile(day, i, days.length, rng));

  for (let i = 0; i < profiles.length; i += 1) {
    const profile = profiles[i]!;
    const window7 = profiles.slice(Math.max(0, i - 6), i + 1);
    const window28 = profiles.slice(Math.max(0, i - 27), i + 1);
    const wau = Math.min(userIds.length, Math.max(...window7.map((p) => p.activeUsers)));
    const mau = Math.min(userIds.length, Math.max(...window28.map((p) => p.activeUsers)));

    await db.transaction(async (tx) => {
      const txDb = tx as unknown as Database;

      const orgRow = {
        orgId: DEMO_ORG_SLUG,
        day: profile.day,
        dailyActiveUsers: profile.activeUsers,
        weeklyActiveUsers: wau,
        monthlyActiveUsers: mau,
        monthlyActiveChatUsers: Math.round(mau * 0.65),
        monthlyActiveAgentUsers: Math.round(mau * 0.3),
        dailyActiveCliUsers: Math.round(profile.activeUsers * 0.15),
        codeAcceptanceActivityCount: profile.totalAccepted,
        codeGenerationActivityCount: profile.totalCompletions,
        locAddedSum: BigInt(profile.totalLocAdded),
        locDeletedSum: BigInt(profile.totalLocDeleted),
        locSuggestedToAddSum: BigInt(profile.totalLocSuggestedAdd),
        locSuggestedToDeleteSum: BigInt(profile.totalLocSuggestedDelete),
        userInitiatedInteractionCount: profile.totalChatInteractions + profile.totalAgentInteractions,
        prTotalCreated: profile.prsCreated,
        prTotalCreatedByCopilot: profile.prsCreatedByCopilot,
        prTotalMerged: profile.prsMerged,
        prTotalMergedCreatedByCopilot: profile.prsMergedByCopilot,
        prTotalReviewed: profile.prsReviewed,
        prTotalReviewedByCopilot: profile.prsReviewedByCopilot,
        prTotalSuggestions: profile.prsCreated * 4,
        prTotalAppliedSuggestions: Math.round(profile.prsCreated * 2.5),
        prTotalCopilotSuggestions: profile.prsCreatedByCopilot * 3,
        prTotalCopilotAppliedSuggestions: Math.round(profile.prsCreatedByCopilot * 2),
        prMedianMinutesToMerge: '180',
        prMedianMinutesToMergeCopilotAuthored: '95',
        prMedianMinutesToMergeCopilotReviewed: '110',
        cliPromptCount: Math.round(profile.activeUsers * 1.5),
        cliRequestCount: Math.round(profile.activeUsers * 2.5),
        cliSessionCount: Math.round(profile.activeUsers * 0.6),
        cliPromptTokensSum: BigInt(profile.activeUsers * 1200),
        cliOutputTokensSum: BigInt(profile.activeUsers * 800),
        ingestedAt: new Date(),
      };
      await txDb.insert(factOrgDaily).values(orgRow).onConflictDoUpdate({
        target: [factOrgDaily.orgId, factOrgDaily.day],
        set: orgRow,
      });

      // by_feature
      const featureCompletionShares = splitByWeightMap(profile.totalCompletions, FEATURE_WEIGHTS);
      const featureAcceptedShares = splitByWeightMap(profile.totalAccepted, FEATURE_WEIGHTS);
      const featureLocAddedShares = splitByWeightMap(profile.totalLocAdded, FEATURE_WEIGHTS);
      const featureLocDeletedShares = splitByWeightMap(profile.totalLocDeleted, FEATURE_WEIGHTS);
      const featureLocSuggestedAddShares = splitByWeightMap(profile.totalLocSuggestedAdd, FEATURE_WEIGHTS);
      const featureLocSuggestedDeleteShares = splitByWeightMap(profile.totalLocSuggestedDelete, FEATURE_WEIGHTS);
      const featureInteractionShares = buildFeatureInteractionShares(profile);
      for (const [feature] of FEATURE_WEIGHTS) {
        const values = {
          orgId: DEMO_ORG_SLUG,
          day: profile.day,
          feature,
          codeGenerationActivityCount: featureCompletionShares.get(feature) ?? 0,
          codeAcceptanceActivityCount: featureAcceptedShares.get(feature) ?? 0,
          locAddedSum: BigInt(featureLocAddedShares.get(feature) ?? 0),
          locDeletedSum: BigInt(featureLocDeletedShares.get(feature) ?? 0),
          locSuggestedToAddSum: BigInt(featureLocSuggestedAddShares.get(feature) ?? 0),
          locSuggestedToDeleteSum: BigInt(featureLocSuggestedDeleteShares.get(feature) ?? 0),
          userInitiatedInteractionCount: featureInteractionShares.get(feature) ?? 0,
        };
        await txDb.insert(factOrgDailyByFeature).values(values).onConflictDoUpdate({
          target: [factOrgDailyByFeature.orgId, factOrgDailyByFeature.day, factOrgDailyByFeature.feature],
          set: values,
        });
      }

      // by_ide
      const ideCompletionShares = splitByWeightMap(profile.totalCompletions, IDE_WEIGHTS);
      const ideAcceptedShares = splitByWeightMap(profile.totalAccepted, IDE_WEIGHTS);
      const ideLocShares = splitByWeightMap(profile.totalLocAdded, IDE_WEIGHTS);
      const ideLocDeletedShares = splitByWeightMap(profile.totalLocDeleted, IDE_WEIGHTS);
      const ideLocSuggestedAddShares = splitByWeightMap(profile.totalLocSuggestedAdd, IDE_WEIGHTS);
      const ideLocSuggestedDeleteShares = splitByWeightMap(profile.totalLocSuggestedDelete, IDE_WEIGHTS);
      const ideInteractionShares = splitByWeightMap(
        profile.totalCompletions + profile.totalChatInteractions + profile.totalAgentInteractions,
        IDE_INTERACTION_WEIGHTS,
      );
      for (const [ide] of IDE_WEIGHTS) {
        const values = {
          orgId: DEMO_ORG_SLUG,
          day: profile.day,
          ide,
          codeAcceptanceActivityCount: ideAcceptedShares.get(ide) ?? 0,
          codeGenerationActivityCount: ideCompletionShares.get(ide) ?? 0,
          locAddedSum: BigInt(ideLocShares.get(ide) ?? 0),
          locDeletedSum: BigInt(ideLocDeletedShares.get(ide) ?? 0),
          locSuggestedToAddSum: BigInt(ideLocSuggestedAddShares.get(ide) ?? 0),
          locSuggestedToDeleteSum: BigInt(ideLocSuggestedDeleteShares.get(ide) ?? 0),
          userInitiatedInteractionCount: ideInteractionShares.get(ide) ?? 0,
        };
        await txDb.insert(factOrgDailyByIde).values(values).onConflictDoUpdate({
          target: [factOrgDailyByIde.orgId, factOrgDailyByIde.day, factOrgDailyByIde.ide],
          set: values,
        });
      }

      // by_language_feature
      for (const [language, langShare] of LANGUAGE_WEIGHTS) {
        for (const [feature, featShare] of FEATURE_WEIGHTS.slice(0, 3)) {
          const accepted = Math.round(profile.totalAccepted * langShare * featShare);
          if (accepted === 0) continue;
          const completions = Math.round(accepted / 0.55);
          const locAdded = Math.round(profile.totalLocAdded * langShare * featShare);
          const values = {
            orgId: DEMO_ORG_SLUG,
            day: profile.day,
            language,
            feature,
            codeAcceptanceActivityCount: accepted,
            codeGenerationActivityCount: completions,
            locAddedSum: BigInt(locAdded),
            locDeletedSum: BigInt(Math.round(locAdded * 0.12)),
            locSuggestedToAddSum: BigInt(Math.round(locAdded / 0.55)),
            locSuggestedToDeleteSum: BigInt(Math.round((locAdded * 0.12) / 0.55)),
            userInitiatedInteractionCount: 0,
          };
          await txDb.insert(factOrgDailyByLanguageFeature).values(values).onConflictDoUpdate({
            target: [
              factOrgDailyByLanguageFeature.orgId,
              factOrgDailyByLanguageFeature.day,
              factOrgDailyByLanguageFeature.language,
              factOrgDailyByLanguageFeature.feature,
            ],
            set: values,
          });
        }
      }

      // by_language_model
      const chatPlusAgent = profile.totalChatInteractions + profile.totalAgentInteractions;
      if (chatPlusAgent > 0) {
        for (const [language, langShare] of LANGUAGE_WEIGHTS) {
          for (const [model, modelShare] of MODEL_WEIGHTS) {
            const count = Math.round(chatPlusAgent * langShare * modelShare);
            if (count === 0) continue;
            const values = {
              orgId: DEMO_ORG_SLUG,
              day: profile.day,
              language,
              model,
              codeAcceptanceActivityCount: Math.round(count * 0.4),
              codeGenerationActivityCount: count,
              locAddedSum: BigInt(Math.round(count * 12)),
              locDeletedSum: BigInt(Math.round(count * 2)),
              locSuggestedToAddSum: BigInt(Math.round(count * 22)),
              locSuggestedToDeleteSum: BigInt(Math.round(count * 4)),
              userInitiatedInteractionCount: 0,
            };
            await txDb.insert(factOrgDailyByLanguageModel).values(values).onConflictDoUpdate({
              target: [
                factOrgDailyByLanguageModel.orgId,
                factOrgDailyByLanguageModel.day,
                factOrgDailyByLanguageModel.language,
                factOrgDailyByLanguageModel.model,
              ],
              set: values,
            });
          }
        }
      }

      // by_model_feature
      for (const [feature] of [
        ...CHAT_INTERACTION_WEIGHTS,
        ['agent', 1] as const,
      ]) {
        const modelInteractionShares = splitByWeightMap(featureInteractionShares.get(feature) ?? 0, MODEL_WEIGHTS);
        for (const [model] of MODEL_WEIGHTS) {
          const count = modelInteractionShares.get(model) ?? 0;
          if (count === 0) continue;
          const values = {
            orgId: DEMO_ORG_SLUG,
            day: profile.day,
            model,
            feature,
            codeAcceptanceActivityCount: Math.round(count * 0.4),
            codeGenerationActivityCount: count,
            locAddedSum: BigInt(Math.round(count * 8)),
            locDeletedSum: BigInt(Math.round(count * 1.5)),
            locSuggestedToAddSum: BigInt(Math.round(count * 15)),
            locSuggestedToDeleteSum: BigInt(Math.round(count * 3)),
            userInitiatedInteractionCount: count,
          };
          await txDb.insert(factOrgDailyByModelFeature).values(values).onConflictDoUpdate({
            target: [
              factOrgDailyByModelFeature.orgId,
              factOrgDailyByModelFeature.day,
              factOrgDailyByModelFeature.model,
              factOrgDailyByModelFeature.feature,
            ],
            set: values,
          });
        }
      }

      // Per-user activity rows
      const userPickCount = Math.min(profile.activeUsers, userIds.length);
      const pickedUsers = userIds.slice(0, userPickCount);
      const userShares = userConsumptionShares(pickedUsers.length);
      for (let u = 0; u < pickedUsers.length; u += 1) {
        const userId = pickedUsers[u]!;
        const share = userShares[u] ?? 0;
        const userAccepted = Math.max(1, Math.round(profile.totalAccepted * share));
        const userCompletions = Math.max(userAccepted, Math.round(profile.totalCompletions * share));
        const userLocAdded = Math.max(1, Math.round(profile.totalLocAdded * share));
        const userInteractionCount = Math.round((profile.totalChatInteractions + profile.totalAgentInteractions) * share);
        const userCliRequests = Math.round((u < 6 ? 5 : 2) * share * profile.activeUsers);
        const usedAgent = u < Math.ceil(pickedUsers.length * 0.25) || rng() < 0.12;
        const usedCli = userCliRequests > 0 || rng() < 0.08;
        const teamId = teamForUserIndex(u, teamIds);
        const userValues = {
          orgId: DEMO_ORG_SLUG,
          userId,
          day: profile.day,
          usedChat: userInteractionCount > 0 || rng() < 0.7,
          usedAgent,
          usedCli,
          codeAcceptanceActivityCount: userAccepted,
          codeGenerationActivityCount: userCompletions,
          locAddedSum: BigInt(userLocAdded),
          locDeletedSum: BigInt(Math.round(userLocAdded * 0.12)),
          locSuggestedToAddSum: BigInt(Math.round(userLocAdded / 0.55)),
          locSuggestedToDeleteSum: BigInt(Math.round((userLocAdded * 0.12) / 0.55)),
          userInitiatedInteractionCount: userInteractionCount,
          cliPromptCount: Math.round(userCliRequests * 0.75),
          cliRequestCount: userCliRequests,
          cliSessionCount: Math.round(userCliRequests * 0.35),
          cliPromptTokensSum: BigInt(Math.round(1500 * userCliRequests)),
          cliOutputTokensSum: BigInt(Math.round(1000 * userCliRequests)),
          ingestedAt: new Date(),
        };
        await txDb.insert(factUserDaily).values(userValues).onConflictDoUpdate({
          target: [factUserDaily.userId, factUserDaily.orgId, factUserDaily.day],
          set: userValues,
        });

        const bridgeValues = { orgId: DEMO_ORG_SLUG, userId, teamId, day: profile.day };
        await txDb.insert(bridgeUserTeam).values(bridgeValues).onConflictDoUpdate({
          target: [bridgeUserTeam.userId, bridgeUserTeam.teamId, bridgeUserTeam.day],
          set: bridgeValues,
        });

        const userFeatureRows = [
          { feature: 'code_completion', accepted: userAccepted, generated: userCompletions, locShare: 0.72, interactions: 0 },
          { feature: 'chat', accepted: 0, generated: 0, locShare: 0.02, interactions: Math.round(userInteractionCount * 0.45) },
          { feature: 'agent', accepted: Math.round(userAccepted * 0.08), generated: Math.round(userCompletions * 0.08), locShare: 0.2, interactions: Math.round(userInteractionCount * 0.35) },
          { feature: 'cli', accepted: 0, generated: 0, locShare: 0.06, interactions: userCliRequests },
        ];
        for (const featureRow of userFeatureRows) {
          const locAdded = Math.round(userLocAdded * featureRow.locShare);
          const featureValues = {
            orgId: DEMO_ORG_SLUG,
            userId,
            day: profile.day,
            feature: featureRow.feature,
            codeAcceptanceActivityCount: featureRow.accepted,
            codeGenerationActivityCount: featureRow.generated,
            locAddedSum: BigInt(locAdded),
            locDeletedSum: BigInt(Math.round(locAdded * 0.12)),
            locSuggestedToAddSum: BigInt(Math.round(locAdded / 0.55)),
            locSuggestedToDeleteSum: BigInt(Math.round((locAdded * 0.12) / 0.55)),
            userInitiatedInteractionCount: featureRow.interactions,
          };
          await txDb.insert(factUserDailyByFeature).values(featureValues).onConflictDoUpdate({
            target: [
              factUserDailyByFeature.userId,
              factUserDailyByFeature.orgId,
              factUserDailyByFeature.day,
              factUserDailyByFeature.feature,
            ],
            set: featureValues,
          });
        }

        const ideValues = {
          orgId: DEMO_ORG_SLUG,
          userId,
          day: profile.day,
          ide: IDES[u % (IDES.length - 1)]!,
          codeAcceptanceActivityCount: userAccepted,
          codeGenerationActivityCount: userCompletions,
          locAddedSum: BigInt(userLocAdded),
          locDeletedSum: BigInt(Math.round(userLocAdded * 0.12)),
          locSuggestedToAddSum: BigInt(Math.round(userLocAdded / 0.55)),
          locSuggestedToDeleteSum: BigInt(Math.round((userLocAdded * 0.12) / 0.55)),
          userInitiatedInteractionCount: 0,
        };
        await txDb.insert(factUserDailyByIde).values(ideValues).onConflictDoUpdate({
          target: [factUserDailyByIde.userId, factUserDailyByIde.orgId, factUserDailyByIde.day, factUserDailyByIde.ide],
          set: ideValues,
        });

        for (const [language, languageShare] of [
          [LANGUAGES[u % (LANGUAGES.length - 1)]!, 0.7],
          [LANGUAGES[(u + 2) % (LANGUAGES.length - 1)]!, 0.3],
        ] as const) {
          const locAdded = Math.round(userLocAdded * languageShare);
          const langFeatValues = {
            orgId: DEMO_ORG_SLUG,
            userId,
            day: profile.day,
            language,
            feature: 'code_completion',
            codeAcceptanceActivityCount: Math.round(userAccepted * languageShare),
            codeGenerationActivityCount: Math.round(userCompletions * languageShare),
            locAddedSum: BigInt(locAdded),
            locDeletedSum: BigInt(Math.round(locAdded * 0.12)),
            locSuggestedToAddSum: BigInt(Math.round(locAdded / 0.55)),
            locSuggestedToDeleteSum: BigInt(Math.round((locAdded * 0.12) / 0.55)),
            userInitiatedInteractionCount: 0,
          };
          await txDb.insert(factUserDailyByLanguageFeature).values(langFeatValues).onConflictDoUpdate({
            target: [
              factUserDailyByLanguageFeature.userId,
              factUserDailyByLanguageFeature.orgId,
              factUserDailyByLanguageFeature.day,
              factUserDailyByLanguageFeature.language,
              factUserDailyByLanguageFeature.feature,
            ],
            set: langFeatValues,
          });
        }

        const modelWeights =
          u % 5 === 0 ? [['gpt-4o-mini', 0.65], ['gpt-4o', 0.2], ['claude-sonnet-4', 0.1], ['gpt-4.1', 0.05]] as const
          : u < 5 ? [['claude-sonnet-4', 0.45], ['gpt-4o', 0.3], ['claude-3.5-sonnet', 0.15], ['o1', 0.1]] as const
          : MODEL_WEIGHTS;
        const userModelInteractions = Math.max(userInteractionCount + Math.round(userCompletions * 0.15), 1);
        const modelShares = splitByWeightMap(userModelInteractions, modelWeights);
        for (const [model] of modelWeights) {
          const count = modelShares.get(model) ?? 0;
          if (count === 0) continue;
          const locAdded = Math.round(userLocAdded * Math.min(0.5, count / Math.max(userModelInteractions, 1)));
          const modelFeatureValues = {
            orgId: DEMO_ORG_SLUG,
            userId,
            day: profile.day,
            model,
            feature: usedAgent ? 'agent' : 'chat',
            codeAcceptanceActivityCount: Math.round(count * 0.25),
            codeGenerationActivityCount: count,
            locAddedSum: BigInt(locAdded),
            locDeletedSum: BigInt(Math.round(locAdded * 0.12)),
            locSuggestedToAddSum: BigInt(Math.round(locAdded / 0.55)),
            locSuggestedToDeleteSum: BigInt(Math.round((locAdded * 0.12) / 0.55)),
            userInitiatedInteractionCount: count,
          };
          await txDb.insert(factUserDailyByModelFeature).values(modelFeatureValues).onConflictDoUpdate({
            target: [
              factUserDailyByModelFeature.userId,
              factUserDailyByModelFeature.orgId,
              factUserDailyByModelFeature.day,
              factUserDailyByModelFeature.model,
              factUserDailyByModelFeature.feature,
            ],
            set: modelFeatureValues,
          });

          const languageModelValues = {
            orgId: DEMO_ORG_SLUG,
            userId,
            day: profile.day,
            language: LANGUAGES[u % (LANGUAGES.length - 1)]!,
            model,
            codeAcceptanceActivityCount: Math.round(count * 0.25),
            codeGenerationActivityCount: count,
            locAddedSum: BigInt(locAdded),
            locDeletedSum: BigInt(Math.round(locAdded * 0.12)),
            locSuggestedToAddSum: BigInt(Math.round(locAdded / 0.55)),
            locSuggestedToDeleteSum: BigInt(Math.round((locAdded * 0.12) / 0.55)),
            userInitiatedInteractionCount: count,
          };
          await txDb.insert(factUserDailyByLanguageModel).values(languageModelValues).onConflictDoUpdate({
            target: [
              factUserDailyByLanguageModel.userId,
              factUserDailyByLanguageModel.orgId,
              factUserDailyByLanguageModel.day,
              factUserDailyByLanguageModel.language,
              factUserDailyByLanguageModel.model,
            ],
            set: languageModelValues,
          });
        }
      }
    });

    if ((i + 1) % 10 === 0 || i === profiles.length - 1) {
      console.log(`  ${i + 1}/${profiles.length} days seeded`);
    }
  }
}

async function seedDemoBilling(db: Database): Promise<void> {
  console.log('• demo: seeding billing + AI credits');
  const seatPriceMonthly = 39;
  const days = daysSequence(addDays(todayUtc(), -DEMO_DAYS + 1), DEMO_DAYS);
  const seats = 35;
  const dailySeatCost = Math.round((seats * seatPriceMonthly / 30) * 100) / 100;
  const dailyPremiumCost = Math.round(seats * 0.22 * 100) / 100;
  for (const day of days) {

    const seatValues = {
      orgId: DEMO_ORG_SLUG,
      day,
      product: 'copilot',
      sku: 'Copilot Enterprise',
      quantity: String(Math.round((seats / 30) * 100) / 100),
      unit: 'UserDays',
      grossAmount: String(dailySeatCost),
      netAmount: String(dailySeatCost),
      currency: 'USD',
    };
    await db.insert(factBillingDaily).values(seatValues).onConflictDoUpdate({
      target: [factBillingDaily.orgId, factBillingDaily.day, factBillingDaily.product, factBillingDaily.sku],
      set: seatValues,
    });

    const premiumValues = {
      orgId: DEMO_ORG_SLUG,
      day,
      product: 'copilot',
      sku: 'Premium request',
      quantity: String(Math.round((seats * 250 / 30) * 100) / 100),
      unit: 'Requests',
      grossAmount: String(dailyPremiumCost),
      netAmount: String(dailyPremiumCost),
      currency: 'USD',
    };
    await db.insert(factBillingDaily).values(premiumValues).onConflictDoUpdate({
      target: [factBillingDaily.orgId, factBillingDaily.day, factBillingDaily.product, factBillingDaily.sku],
      set: premiumValues,
    });

    for (const [model, modelShare] of MODEL_WEIGHTS) {
      const aiCreditValues = {
        orgId: DEMO_ORG_SLUG,
        day,
        model,
        feature: 'chat',
        includedQuantity: String(Math.round(seats * 4 * modelShare)),
        billedQuantity: String(Math.round(seats * 0.9 * modelShare * 100) / 100),
        billedAmount: String(Math.round(seats * 0.04 * modelShare * 100) / 100),
        currency: 'USD',
      };
      await db.insert(factAiCreditsDaily).values(aiCreditValues).onConflictDoUpdate({
        target: [factAiCreditsDaily.orgId, factAiCreditsDaily.day, factAiCreditsDaily.model, factAiCreditsDaily.feature],
        set: aiCreditValues,
      });
    }
  }
}

// ============================================================================
// Step 4: gold rebuild for demo org
// ============================================================================

async function loadKnobs(db: Database): Promise<ValueKnobs> {
  const row = await db.select().from(settings).where(eq(settings.key, VALUE_TRANSLATION_KNOBS_KEY)).limit(1);
  const stored = row[0]?.value as Partial<ValueKnobs> | undefined;
  if (!stored) return DEFAULT_KNOBS;
  return { ...DEFAULT_KNOBS, ...stored, blend: { ...DEFAULT_KNOBS.blend, ...(stored.blend ?? {}) } };
}

function releaseRowsToEvents(
  rows: Array<typeof factReleaseDaily.$inferSelect>,
  releaseWindowDay?: string,
): ReleaseEvent[] {
  return rows.flatMap((row) => {
    const day = row.day;
    const latestTagAt = row.latestTagAt ?? dateAtUtc(day, 16, 0);
    return Array.from({ length: row.releaseCount }, (_, i) => {
      const isPrerelease = i < row.prereleaseCount;
      const tagAt =
        releaseWindowDay && day !== releaseWindowDay ?
          latestTagAt
        : new Date(latestTagAt.getTime() - Math.max(0, row.releaseCount - i - 1) * 45 * 60_000);
      return { day, isPrerelease, tagAt };
    });
  });
}

function commitRowsToEvents(rows: Array<typeof factCommitDaily.$inferSelect>): CommitEvent[] {
  return rows.flatMap((row) =>
    Array.from({ length: row.commitCount }, (_, i) => ({
      day: row.day,
      authoredAt: dateAtUtc(row.day, 8 + (i % 5), (Number(row.authorUserId % 53n) + i * 7) % 60),
    })),
  );
}

function workflowRowsToRuns(rows: Array<typeof factWorkflowRunDaily.$inferSelect>): WorkflowRun[] {
  return rows.flatMap((row) => {
    const runs: WorkflowRun[] = [];
    const durationSec = Number(row.medianDurationSec);
    const workflowId = Number(row.workflowId);
    const flakyCandidate = workflowId % 3 === 0 && row.successCount > 0;

    for (let i = 0; i < row.failureCount; i += 1) {
      const startedAt = dateAtUtc(row.day, flakyCandidate && i === 0 ? 9 : 16, i % 60);
      runs.push({
        workflowId,
        conclusion: 'failure',
        startedAt,
        completedAt: new Date(startedAt.getTime() + Math.round(durationSec * 1.15) * 1_000),
        attempt: 1,
      });
    }
    for (let i = 0; i < row.successCount; i += 1) {
      const startedAt = dateAtUtc(row.day, flakyCandidate ? 9 : 10, 20 + (i % 35));
      runs.push({
        workflowId,
        conclusion: 'success',
        startedAt,
        completedAt: new Date(startedAt.getTime() + durationSec * 1_000),
        attempt: flakyCandidate && i === 0 ? 2 : 1,
      });
    }
    for (let i = 0; i < row.cancelledCount; i += 1) {
      const startedAt = dateAtUtc(row.day, 12, i % 60);
      runs.push({
        workflowId,
        conclusion: 'cancelled',
        startedAt,
        completedAt: new Date(startedAt.getTime() + Math.round(durationSec * 0.4) * 1_000),
        attempt: 1,
      });
    }
    return runs;
  });
}

async function rebuildDeliveryGoldForOrg(db: Database, orgId: string, days: readonly string[]): Promise<void> {
  const deliveryValue = await loadDeliveryValueFunctions();
  await db.delete(factDoraDaily).where(eq(factDoraDaily.orgId, orgId));
  await db.delete(factCiDaily).where(eq(factCiDaily.orgId, orgId));

  const releaseRows = await db.select().from(factReleaseDaily).where(eq(factReleaseDaily.orgId, orgId));
  const commitRows = await db.select().from(factCommitDaily).where(eq(factCommitDaily.orgId, orgId));
  const workflowRows = await db.select().from(factWorkflowRunDaily).where(eq(factWorkflowRunDaily.orgId, orgId));

  for (let i = 0; i < days.length; i += 1) {
    const day = days[i]!;
    const trailingDays = days.slice(Math.max(0, i - 6), i + 1);
    const releasesInWindow = releaseRowsToEvents(releaseRows.filter((row) => trailingDays.includes(row.day)));
    const releasesToday = releaseRowsToEvents(releaseRows.filter((row) => row.day === day), day);
    const commitsToday = commitRowsToEvents(commitRows.filter((row) => row.day === day));
    const workflowRunsToday = workflowRowsToRuns(workflowRows.filter((row) => row.day === day));
    void deliveryValue.changeFailureRate(releasesToday, []);

    const doraValues = {
      orgId,
      day,
      deploymentFrequency: toNumeric(deliveryValue.deploymentFrequency(releasesInWindow, trailingDays.length)),
      leadTimeMin: toNumeric(deliveryValue.leadTimeForChanges(commitsToday, releasesToday)),
      changeFailureRate: null,
      mttrMin: toNumeric(deliveryValue.meanTimeToRestore([])),
    };
    await db.insert(factDoraDaily).values(doraValues).onConflictDoUpdate({
      target: [factDoraDaily.orgId, factDoraDaily.day],
      set: doraValues,
    });

    const ciValues = {
      orgId,
      day,
      ciSuccessRate: toNumeric(deliveryValue.ciSuccessRate(workflowRunsToday)),
      medianTimeToGreenSec: toNumeric(deliveryValue.medianTimeToGreen(workflowRunsToday)),
      flakyTestRate: toNumeric(deliveryValue.flakyTestRate(workflowRunsToday)),
    };
    await db.insert(factCiDaily).values(ciValues).onConflictDoUpdate({
      target: [factCiDaily.orgId, factCiDaily.day],
      set: ciValues,
    });
  }
}

async function rebuildGoldForOrg(db: Database, orgId: string): Promise<void> {
  console.log(`• gold: rebuilding for "${orgId}"`);
  const knobs = await loadKnobs(db);
  const snapshot = snapshotKnobs(knobs) as unknown as Record<string, unknown>;

  await db.delete(factValueDaily).where(eq(factValueDaily.orgId, orgId));
  await db.delete(factRoiDaily).where(eq(factRoiDaily.orgId, orgId));

  const orgDays = await db
    .select()
    .from(factOrgDaily)
    .where(eq(factOrgDaily.orgId, orgId))
    .orderBy(factOrgDaily.day);

  for (const orgDay of orgDays) {
    const day = orgDay.day;

    const accepted = await db
      .select({ sum: sql<string>`coalesce(sum(${factOrgDailyByFeature.codeAcceptanceActivityCount}), 0)` })
      .from(factOrgDailyByFeature)
      .where(and(
        eq(factOrgDailyByFeature.orgId, orgId),
        eq(factOrgDailyByFeature.day, day),
        eq(factOrgDailyByFeature.feature, 'code_completion'),
      ));
    const chatRows = await db
      .select({ sum: sql<string>`coalesce(sum(${factOrgDailyByFeature.userInitiatedInteractionCount}), 0)` })
      .from(factOrgDailyByFeature)
      .where(and(
        eq(factOrgDailyByFeature.orgId, orgId),
        eq(factOrgDailyByFeature.day, day),
        inArray(factOrgDailyByFeature.feature, ['chat', 'ask', 'edit', 'plan']),
      ));
    const agentSessionsRow = await db
      .select({ sum: sql<string>`coalesce(count(*), 0)` })
      .from(factUserDaily)
      .where(and(eq(factUserDaily.orgId, orgId), eq(factUserDaily.day, day), eq(factUserDaily.usedAgent, true)));

    const acceptedCompletions = Number(accepted[0]?.sum ?? 0);
    const chatRequests = Number(chatRows[0]?.sum ?? 0);
    const agentSessions = Number(agentSessionsRow[0]?.sum ?? 0);

    const seatCostRow = await db
      .select({ sum: sql<string>`coalesce(sum(${factBillingDaily.netAmount}), 0)` })
      .from(factBillingDaily)
      .where(and(
        eq(factBillingDaily.orgId, orgId),
        eq(factBillingDaily.day, day),
        eq(factBillingDaily.product, 'copilot'),
        eq(factBillingDaily.sku, 'Copilot Enterprise'),
      ));
    const premiumRow = await db
      .select({ sum: sql<string>`coalesce(sum(${factBillingDaily.netAmount}), 0)` })
      .from(factBillingDaily)
      .where(and(
        eq(factBillingDaily.orgId, orgId),
        eq(factBillingDaily.day, day),
        eq(factBillingDaily.product, 'copilot'),
        ne(factBillingDaily.sku, 'Copilot Enterprise'),
      ));
    const creditRow = await db
      .select({ sum: sql<string>`coalesce(sum(${factAiCreditsDaily.billedAmount}), 0)` })
      .from(factAiCreditsDaily)
      .where(and(eq(factAiCreditsDaily.orgId, orgId), eq(factAiCreditsDaily.day, day)));

    const spend: SpendDailyInputs = {
      seatCost: Number(seatCostRow[0]?.sum ?? 0),
      premiumRequestSpend: Number(premiumRow[0]?.sum ?? 0),
      aiCreditSpend: Number(creditRow[0]?.sum ?? 0),
    };

    const result = computeDailyValue(
      {
        orgId,
        day,
        acceptedCompletions,
        chatRequests,
        agentSessions,
        locAddedByCopilot: Number(orgDay.locAddedSum ?? 0n),
        prMergedByCopilot: orgDay.prTotalMergedCreatedByCopilot,
        prReviewedByCopilot: orgDay.prTotalReviewedByCopilot,
      },
      spend,
      knobs,
    );

    for (const estimator of Object.values(result.estimators)) {
      await db.insert(factValueDaily).values({
        orgId,
        day,
        estimator: estimator.estimator,
        hoursSaved: String(estimator.hoursSaved),
        dollarsSaved: String(estimator.dollarsSaved),
        knobSnapshot: snapshot,
      });
    }

    await db.insert(factRoiDaily).values({
      orgId,
      day,
      hoursSavedBlended: String(result.blended.hoursSaved),
      dollarsSavedBlended: String(result.blended.dollarsSaved),
      totalSpend: String(result.roi.totalSpend),
      netValue: String(result.roi.netValue),
      roiRatio: String(result.roi.roiRatio),
    });
  }

  await rebuildDeliveryGoldForOrg(db, orgId, orgDays.map((row) => row.day));
}

// ============================================================================
// Cleanup helpers
// ============================================================================

async function clearDemoData(db: Database): Promise<void> {
  console.log(`• clear-demo: wiping all data for "${DEMO_ORG_SLUG}"`);
  await db.transaction(async (tx) => {
    const t = tx as unknown as Database;
    await t.delete(factDoraDaily).where(eq(factDoraDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factCiDaily).where(eq(factCiDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factCommitDaily).where(eq(factCommitDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factWorkflowRunDaily).where(eq(factWorkflowRunDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factReleaseDaily).where(eq(factReleaseDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factAiCreditsDaily).where(eq(factAiCreditsDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factBillingDaily).where(eq(factBillingDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDailyByFeature).where(eq(factOrgDailyByFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDailyByIde).where(eq(factOrgDailyByIde.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDailyByLanguageFeature).where(eq(factOrgDailyByLanguageFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDailyByLanguageModel).where(eq(factOrgDailyByLanguageModel.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDailyByModelFeature).where(eq(factOrgDailyByModelFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDailyByFeature).where(eq(factUserDailyByFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDailyByIde).where(eq(factUserDailyByIde.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDailyByLanguageFeature).where(eq(factUserDailyByLanguageFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDailyByLanguageModel).where(eq(factUserDailyByLanguageModel.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDailyByModelFeature).where(eq(factUserDailyByModelFeature.orgId, DEMO_ORG_SLUG));
    await t.delete(factUserDaily).where(eq(factUserDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(bridgeUserTeam).where(eq(bridgeUserTeam.orgId, DEMO_ORG_SLUG));
    await t.delete(factOrgDaily).where(eq(factOrgDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factValueDaily).where(eq(factValueDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factRoiDaily).where(eq(factRoiDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(factTeamValueDaily).where(eq(factTeamValueDaily.orgId, DEMO_ORG_SLUG));
    await t.delete(ingestionRun).where(eq(ingestionRun.orgId, DEMO_ORG_SLUG));
    await t.delete(dimRepo).where(eq(dimRepo.orgId, DEMO_ORG_SLUG));
    await t.delete(dimTeam).where(eq(dimTeam.orgId, DEMO_ORG_SLUG));
    await t.delete(dimUser).where(sql`${dimUser.userId} >= 900000000 AND ${dimUser.userId} < 910000000`);
    await t.delete(dimOrg).where(eq(dimOrg.orgId, DEMO_ORG_SLUG));
  });
}

async function resetAllFacts(db: Database): Promise<void> {
  console.log('• reset: wiping ALL silver/gold/ingestion data');
  await db.transaction(async (tx) => {
    const t = tx as unknown as Database;
    await t.delete(factDoraDaily);
    await t.delete(factCiDaily);
    await t.delete(factCommitDaily);
    await t.delete(factWorkflowRunDaily);
    await t.delete(factReleaseDaily);
    await t.delete(factAiCreditsDaily);
    await t.delete(factBillingDaily);
    await t.delete(factOrgDailyByFeature);
    await t.delete(factOrgDailyByIde);
    await t.delete(factOrgDailyByLanguageFeature);
    await t.delete(factOrgDailyByLanguageModel);
    await t.delete(factOrgDailyByModelFeature);
    await t.delete(factUserDailyByFeature);
    await t.delete(factUserDailyByIde);
    await t.delete(factUserDailyByLanguageFeature);
    await t.delete(factUserDailyByLanguageModel);
    await t.delete(factUserDailyByModelFeature);
    await t.delete(factUserDaily);
    await t.delete(bridgeUserTeam);
    await t.delete(factOrgDaily);
    await t.delete(factValueDaily);
    await t.delete(factRoiDaily);
    await t.delete(factTeamValueDaily);
    await t.delete(ingestionRun);
    await t.delete(dimRepo).where(isNotNull(dimRepo.repoId));
    await t.delete(dimTeam).where(isNotNull(dimTeam.teamId));
    await t.delete(dimUser).where(isNotNull(dimUser.userId));
    await t.delete(dimOrg).where(isNotNull(dimOrg.orgId));
  });
}

// ============================================================================
// Main
// ============================================================================

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    printHelp();
    return;
  }
  if (opts.reset && !opts.yes) {
    console.error('--reset is dangerous and requires --yes (or -y) to confirm.');
    process.exitCode = 1;
    return;
  }

  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL is required to seed the database.');

  const db = createDb(url);

  if (opts.reset) {
    await resetAllFacts(db);
  }
  if (opts.clearDemo) {
    await clearDemoData(db);
  }

  await seedDimensions(db);
  await seedSettings(db);

  if (opts.demo) {
    await seedDemoOrg(db);
    const userIds = await seedDemoUsers(db, 35);
    const teamIds = await seedDemoTeams(db);
    const repoIds = await seedDemoRepos(db);
    await seedDemoFacts(db, userIds, teamIds);
    await seedDemoBilling(db);
    await seedDemoDeliveryFacts(db, repoIds, userIds);
    await rebuildGoldForOrg(db, DEMO_ORG_SLUG);
  }

  console.log('✅ seed complete');
}

await main();
process.exit(process.exitCode ?? 0);
