'use client';
import Link from 'next/link';
import { Info } from 'lucide-react';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from './ui/dialog';

type MetricId = 'dollars-saved-mtd' | 'hours-saved-mtd' | 'roi' | 'acceptance-rate' | 'delivery-hours' | 'cost-per-active-user' | 'unit-cost-per-pr' | 'unit-cost-per-kloc' | 'unit-cost-per-copilot-pr' | 'dollar-per-active-user-trend' | 'unit-economics-over-time' | 'value-basis' | 'net-value' | 'active-users-wow-delta' | 'acceptance-rate-wow-delta' | 'dollars-saved-wow-delta' | 'prs-by-copilot-wow-delta' | 'calculator-savings' | 'consumption-top20' | 'consumption-top10' | 'consumption-top-team' | 'premium-model-spend-share' | 'cost-conscious-share' | 'cost-conscious-score' | 'user-acceptance-rate' | 'deployment-frequency' | 'lead-time' | 'change-failure-rate' | 'mttr' | 'ci-success-rate' | 'time-to-green' | 'commits-per-day' | 'pr-rework-rate' | 'dependabot-open' | 'test-stability';
const formulas: Record<MetricId, { title: string; formula: string; knobs: string[] }> = {
  'dollars-saved-mtd': { title: 'Dollars saved', formula: 'Dollars saved = blended hours saved × average loaded engineering cost per hour. By default the blend is 100% delivery-based.', knobs: ['avgLoadedEngCostPerHour', 'blend'] },
  'hours-saved-mtd': { title: 'Hours saved', formula: 'Hours saved is the configured blend of activity, output, and delivery estimators.', knobs: ['minPerAcceptedCompletion', 'minPerChatRequest', 'minPerAgentSession', 'minSavedPerAuthoredPr', 'minSavedPerReviewedPr', 'locPerHourBaseline', 'blend'] },
  roi: { title: 'ROI', formula: 'ROI = (dollars saved blended − total spend) ÷ total spend.', knobs: ['blend', 'avgLoadedEngCostPerHour'] },
  'acceptance-rate': { title: 'Acceptance rate', formula: 'Acceptance rate = accepted completions ÷ generated suggestions/interactions.', knobs: [] },
  'delivery-hours': { title: 'Delivery-based hours', formula: 'Hours saved = (Copilot-authored merged PRs × minutes saved per authored PR + Copilot-reviewed PRs × minutes saved per reviewed PR) ÷ 60.', knobs: ['minSavedPerAuthoredPr', 'minSavedPerReviewedPr'] },
  'cost-per-active-user': { title: 'Cost per active user', formula: 'Cost per active user = total spend for the period ÷ monthly active users.', knobs: [] },
  'unit-cost-per-pr': { title: 'Cost per merged PR', formula: 'Cost per merged PR = total spend for the selected period ÷ merged PRs in the selected period. If merged PRs is 0, the value is —.', knobs: [] },
  'unit-cost-per-kloc': { title: 'Cost per 1k LoC delivered', formula: 'Cost per 1k LoC delivered = total spend for the selected period × 1,000 ÷ LoC added in the selected period. LoC is directional output, not a value measure. If LoC added is 0, the value is —.', knobs: [] },
  'unit-cost-per-copilot-pr': { title: 'Cost per Copilot-authored PR', formula: 'Cost per Copilot-authored PR = total spend for the selected period ÷ Copilot-authored merged PRs in the selected period. If Copilot-authored merged PRs is 0, the value is —.', knobs: [] },
  'dollar-per-active-user-trend': { title: 'Cost per active user (trend)', formula: 'For each day, cost per active user = that day\'s total spend ÷ that day\'s monthly active users. Days with zero MAU render as gaps, never $0. The sparkline plots this across the selected window.', knobs: [] },
  'unit-economics-over-time': { title: 'Unit economics over time', formula: 'Each line divides that day\'s total spend by that day\'s denominator (merged PRs, MAU, LoC added ÷ 1k, or Copilot-authored merged PRs). Null daily points are gaps, not zero-value dips.', knobs: [] },
  'value-basis': { title: 'Headline basis', formula: 'The headline $ saved is driven by the configured estimator blend (weights sum to 1.0). By default the blend is 100% Delivery-based — the most conservative, delivery-tied estimator. Change the blend in Settings.', knobs: ['blend'] },
  'net-value': { title: 'Net value', formula: 'Net value = dollars saved (blended) − total spend (seats + premium requests + AI credits) over the selected period. ROI = net value ÷ total spend. Negative values are shown explicitly.', knobs: ['blend', 'avgLoadedEngCostPerHour'] },
  'active-users-wow-delta': { title: 'Active users week-over-week delta', formula: 'Active users Δ = (current 7-day MAU − prior 7-day MAU) ÷ max(prior 7-day MAU, 1).', knobs: [] },
  'acceptance-rate-wow-delta': { title: 'Acceptance rate week-over-week delta', formula: 'Acceptance rate Δ = current 7-day acceptance rate − prior 7-day acceptance rate, shown as percentage points.', knobs: [] },
  'dollars-saved-wow-delta': { title: 'Dollars saved week-over-week delta', formula: 'Dollars saved Δ = current 7-day dollars saved − prior 7-day dollars saved.', knobs: ['blend', 'avgLoadedEngCostPerHour'] },
  'prs-by-copilot-wow-delta': { title: 'PRs by Copilot week-over-week delta', formula: 'PRs by Copilot Δ = current 7-day Copilot PR count − prior 7-day Copilot PR count.', knobs: [] },
  'calculator-savings': { title: 'Calculator savings', formula: 'Uses the same value engine with manually entered team activity: completions, chat, agent sessions, and Copilot-touched PRs.', knobs: ['avgLoadedEngCostPerHour', 'minPerAcceptedCompletion', 'minPerChatRequest', 'minPerAgentSession', 'minSavedPerAuthoredPr'] },
  'consumption-top20': { title: 'Top 20% consumption share', formula: 'Users are sorted by measured consumption units: user-initiated interactions + code generation activity + CLI requests. This metric is the top 20% cohort consumption divided by total consumption in the selected period. It renders as unavailable until the cohort contains at least 5 users.', knobs: [] },
  'consumption-top10': { title: 'Top 10% consumption share', formula: 'Users are sorted by measured consumption units: user-initiated interactions + code generation activity + CLI requests. This metric is the top 10% cohort consumption divided by total consumption in the selected period. It renders as unavailable until the cohort contains at least 5 users.', knobs: [] },
  'consumption-top-team': { title: 'Top team consumption share', formula: 'Team consumption is computed from bridge_user_team joined to fact_user_daily at user/day grain. Teams with fewer than 5 active users are suppressed. Users in multiple teams contribute to each joined team, so this is an attribution share, not a strict allocation that sums to 100%.', knobs: [] },
  'premium-model-spend-share': { title: 'Premium model spend share', formula: 'Premium model spend share = billed AI-credit amount for non-mini/small/nano models ÷ total billed AI-credit amount in the selected period. It renders as unavailable when AI-credit billing facts were not ingested.', knobs: [] },
  'cost-conscious-share': { title: 'Cost-conscious share', formula: 'Cost-conscious share = included AI-credit quantity ÷ (included AI-credit quantity + billed AI-credit quantity). Higher means more model usage is staying inside included pools. It renders as unavailable when AI-credit billing facts were not ingested.', knobs: [] },
  'cost-conscious-score': { title: 'Cost-conscious team score', formula: 'For each team above the privacy threshold, estimated billed model amount is allocated from model-level billed spend using normalized user model usage. If billing and usage model names do not align exactly, an org-wide model unit-cost fallback is used. Score = (team consumption ÷ (estimated billed amount + 1)) normalized to the highest team in the selected range.', knobs: [] },
  'user-acceptance-rate': { title: 'User acceptance rate', formula: 'Acceptance rate = accepted completions ÷ generated suggestions/interactions for this selected user and date range.', knobs: [] },
  'deployment-frequency': { title: 'Deployment frequency', formula: 'Deployment frequency = count of non-draft releases in the selected window ÷ days in the selected window.', knobs: [] },
  'lead-time': { title: 'Lead time for changes', formula: 'Lead time = median minutes from commit author timestamp to first release published_at containing that commit. Null means the sample is insufficient.', knobs: [] },
  'change-failure-rate': { title: 'Change failure rate', formula: 'Change failure rate = failed release count ÷ release count, where failed releases are followed by a hotfix or revert within the configured detection window.', knobs: [] },
  mttr: { title: 'MTTR', formula: 'MTTR = median minutes from incident or critical-bug issue created_at to closed_at. Open incidents are excluded from the median.', knobs: [] },
  'ci-success-rate': { title: 'CI success rate', formula: 'CI success rate = successful completed GitHub Actions runs ÷ completed runs. Cancelled/skipped runs are excluded by ingestion policy.', knobs: [] },
  'time-to-green': { title: 'Time to green', formula: 'Time-to-green = median seconds from push/head commit timestamp to the first successful CI run for the same commit.', knobs: [] },
  'commits-per-day': { title: 'Commits per day', formula: 'Commits per day = sum of privacy-preserving daily commit aggregates ÷ days in the selected window. No per-developer rows are shown.', knobs: [] },
  'pr-rework-rate': { title: 'PR rework rate', formula: 'PR rework rate = median commits pushed after first review per merged PR. Null means this source is not ingested yet.', knobs: [] },
  'dependabot-open': { title: 'Dependabot open alerts', formula: 'Dependabot open = count of open Dependabot alerts in the selected org. Null means Dependabot ingestion is not enabled yet.', knobs: [] },
  'test-stability': { title: 'Test stability', formula: 'Test stability = 1 − flaky test rate. In v1, flaky test rate uses GitHub Actions re-run success-after-failure as a proxy.', knobs: [] },
};
export function HowCalculatedPanel({ metric, inputs }: { metric: MetricId; inputs?: Record<string, number | string> }) {
  const item = formulas[metric];
  return <Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" className="h-7 w-7"><Info className="h-4 w-4" /><span className="sr-only">How is this calculated?</span></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{item.title}</DialogTitle><DialogDescription>How is this calculated?</DialogDescription></DialogHeader><div className="space-y-4 text-sm"><p>{item.formula}</p>{item.knobs.length > 0 && <div><p className="font-medium">Knobs used</p><ul className="mt-1 list-disc pl-5 text-muted-foreground">{item.knobs.map((k) => <li key={k}>{k}</li>)}</ul></div>}{inputs && <div><p className="font-medium">Current inputs</p><dl className="mt-1 grid grid-cols-2 gap-2 text-muted-foreground">{Object.entries(inputs).map(([k, v]) => <div key={k} className="contents"><dt>{k}</dt><dd className="text-right">{v}</dd></div>)}</dl></div>}<Link className="text-link underline" href="/settings">View settings</Link></div></DialogContent></Dialog>;
}
