'use client';
import { useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { CALCULATOR_DEFAULTS, computeCalculator, type CalculatorInputs } from '@/calculator/compute';
import { KpiTile } from '@/components/kpi-tile';
import { ChartShell } from '@/components/chart-shell';
import { HorizontalBarChart } from '@/components/charts/horizontal-bar';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { formatCurrency, formatHours, formatPercent } from '@/lib/format';
const keys = Object.keys(CALCULATOR_DEFAULTS) as (keyof CalculatorInputs)[];
function readParams(params: URLSearchParams): CalculatorInputs { return Object.fromEntries(keys.map(k => [k, Number(params.get(k)) || CALCULATOR_DEFAULTS[k]])) as unknown as CalculatorInputs; }
export function CalculatorView() { const params=useSearchParams(); const router=useRouter(); const [input,setInput]=useState<CalculatorInputs>(()=>readParams(params)); const result=useMemo(()=>computeCalculator(input),[input]); function set<K extends keyof CalculatorInputs>(k:K,v:number){const next={...input,[k]:v}; setInput(next); const q=new URLSearchParams(); keys.forEach(key=>q.set(key,String(next[key]))); router.replace(`/calculator?${q.toString()}`, { scroll:false });} const copy=async()=>navigator.clipboard.writeText(`Copilot estimate: ${formatCurrency(result.roi.dollarsSavedBlended)}/month, ${formatHours(result.roi.hoursSavedBlended)}, ROI ${formatPercent(result.roi.roiRatio)}`); return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Cost-Savings Calculator</h1><p className="text-muted-foreground">Public standalone estimator. No database or API required.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_420px]"><Card><CardHeader><CardTitle>Inputs</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{keys.map(k=><div key={k} className="space-y-2"><Label htmlFor={k}>{k}</Label><Input id={k} type="number" value={input[k]} onChange={e=>set(k, Number(e.target.value))} step={k.includes('pct') || k.includes('min') ? '0.25':'1'} /></div>)}<div className="flex gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={()=>setInput(CALCULATOR_DEFAULTS)}>Reset to defaults</Button></div></CardContent></Card><aside className="space-y-4 lg:sticky lg:top-24 lg:self-start"><div className="grid gap-4"><KpiTile label="$ saved / month" value={result.roi.dollarsSavedBlended} format="dollars" howCalculated={{metric:'calculator-savings',inputs:{activeDevs:result.activeDevs}}}/><KpiTile label="Hours saved / month" value={result.roi.hoursSavedBlended} format="hours"/><KpiTile label="ROI" value={result.roi.roiRatio} format="percent"/><KpiTile label="Payback" value={Number.isFinite(result.paybackMonths)?result.paybackMonths:0} format="raw" hint={result.paybackMonths < 1 ? '< 1 month' : `${result.paybackMonths.toFixed(1)} months`} /></div><ChartShell title="Contribution by source"><HorizontalBarChart data={result.contributions} nameKey="source" valueKey="hours" /></ChartShell><div className="flex flex-wrap gap-2 no-print"><Button onClick={copy}>Copy results</Button><Button variant="outline" onClick={()=>window.print()}>Print PDF</Button><Button variant="outline" onClick={()=>navigator.clipboard.writeText(window.location.href)}>Share link</Button></div></aside></div></div>; }
